"""initial empty schema

Revision ID: 66fcee048c39
Revises:
Create Date: 2026-09-09 18:19:03.569175

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "66fcee048c39"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
